name: Destroy dev deployment

on:
  pull_request:
    types: [ closed ]

env:
  service: dev-semver-sandbox
  version: pull-request-${{ github.event.pull_request.number }}

jobs:
  destroy-dev:
    name: Destroy dev deployment
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '314.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Delete PR deployment
        run: gcloud app version delete ${{ env.version }} --service=${{ env.service }} --quiet

      - name: Destroy GitHub dev deployment
        uses: bobheadxi/deployments@v0.4.2
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: dev
          desc: Deployment was pruned