name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate url to edit draft
        id: url-draft-edit
        run: echo "::set-output name=this::`echo ${{ steps.draft.outputs.html_url }} | sed 's/releases\/tag/releases\/edit/'`"
      - name: Escape release note
        id: escape-note
        uses: actions/github-script@v3
        with:
          script: return `${{ steps.draft.outputs.body }}`.replace(/\n/g, '\\n');
          result-encoding: string
      - uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ci
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}> の main へ新しい push がありました。\n現在の GitHub リリースドラフトは <${{ steps.draft.outputs.html_url }}|${{ steps.draft.outputs.name }}> です。"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*リポジトリ:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*次のリリース:*\n<${{ steps.draft.outputs.html_url }}|${{ steps.draft.outputs.tag_name }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*リリースノート:*\n${{ steps.escape-note.outputs.result }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "リリースノートを編集"
                      },
                      "style": "primary",
                      "url": "${{ steps.url-draft-edit.outputs.this }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": "リリースを publish するとビルドとデプロイも実行されます。",
                      "emoji": true
                    }
                  ]
                }
              ]
            }