name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate url to edit draft
        id: url-draft-edit
        uses: actions/github-script@v3
        with:
          script: return "${{ steps.draft.outputs.html_url }}".replace(/releases\/tag/, 'releases\/edit');
          result-encoding: string
      - name: Escape release note
        id: escape-note
        uses: actions/github-script@v3
        with:
          script: return `${{ steps.draft.outputs.body }}`.replace(/\n/g, '\\n');
          result-encoding: string
      - uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ci
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}> の下書きリリースが更新されました。",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                      "type": "mrkdwn",
                      "text": "*次のリリース:*\n<${{ steps.draft.outputs.html_url }}|${{ steps.draft.outputs.tag_name }}>"
                    }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*リリースノート (下書き):*\n${{ steps.escape-note.outputs.result }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "リリースノートを編集"
                      },
                      "style": "primary",
                      "url": "${{ steps.url-draft-edit.outputs.result }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": "リリースを publish するとビルドとデプロイも実行されます。",
                      "emoji": true
                    }
                  ]
                }
              ]
            }