name: Draft Release

on:
  push:
    branches:
      - main

env:
  channel: C01DC7NL1QU

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate url to edit draft
        id: url-draft-edit
        uses: actions/github-script@v3
        with:
          script: return "${{ steps.draft.outputs.html_url }}".replace(/releases\/tag/, 'releases\/edit');
          result-encoding: string
      - name: Escape release note
        id: escape-note
        uses: actions/github-script@v3
        with:
          script: return `${{ steps.draft.outputs.body }}`.replace(/\n/g, '\\n');
          result-encoding: string
      - name: Notify release note update
        uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ env.channel }}
          message: ':memo: ${{ github.repository }} の下書きリリースノートが更新されました。'
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo: <https://github.com/${{ github.repository }}|${{ github.repository }}> の下書きリリースノート <${{ steps.draft.outputs.html_url }}|${{ steps.draft.outputs.tag_name }}> が更新されました。"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```\n${{ steps.escape-note.outputs.result }}\n```"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "リリースノートを編集"
                      },
                      "style": "primary",
                      "url": "${{ steps.url-draft-edit.outputs.result }}"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "package.json & tag の更新"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions?query=workflow%3AVersion",
                      "confirm": {
                        "title": {
                          "type": "plain_text",
                          "text": "リリースの準備はできましたか?"
                        },
                        "text": {
                          "type": "mrkdwn",
                          "text": "package.json と tag を次のリリースバージョンに更新し、デフォルトブランチに直接コミットします。\nリリース内容が固まったら実行してください。"
                        },
                        "confirm": {
                          "type": "plain_text",
                          "text": "更新ページを開いてバージョンを入力する"
                        },
                        "deny": {
                          "type": "plain_text",
                          "text": "まだしない"
                        }
                      }
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "plain_text",
                      "text": "リリースを publish すると、 production へのデプロイとロールアウトが実行されます。",
                      "emoji": true
                    }
                  ]
                },
             		{
                  "type": "divider"
                }
              ]
            }