name: Label Pull Requests
on:
  pull_request:
    types: [opened]

jobs:
  Labeling:
    name: Labeling
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}