name: Verify Pull Request Labels
on:
  pull_request:
    branches: [main]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    name: Check label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "release/major, release/minor, release/patch"