name: Verify release pull request

on:
  pull_request:
    branches: [main]
    types: [opened, labeled, unlabeled, synchronize]


jobs:
  Verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Verify release label
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'release/major, release/minor, release/patch'