name: Version

on:
  workflow_dispatch:

env:
  mrkdwn_action_log_link: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|(log)>
  channel: C01DC7NL1QU

jobs:
  update-package-json-and-tag:
    name: Update package.json and tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get draft release version
        id: version
        uses: actions/github-script@v3
        with:
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            const releases = response.data;
            const latest = releases[0];
            if (latest.draft) {
              return latest.tag_name;
            } else {
              core.setFailed("Assumed the latest release was draft, but actually not.");
            }
          result-encoding: string

      - name: Set Node up
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Update package.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn config set version-git-message "%s"
          yarn config set version-tag-prefix ""
          yarn version --new-version ${{ steps.version.outputs.result }}
          git push

      - name: Push version tag
        run: git push origin refs/tags/${{ steps.version.outputs.result }}

      - name: Get commit hash
        id: commit-hash
        run: echo "::set-output name=this::`git rev-parse HEAD`"

      - name: Notify success
        uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ env.channel }}
          message: ':up: <https://github.com/${{ github.repository }}|${{ github.repository }}> の package.json と tag を ${{ steps.version.outputs.result }} に更新しました。 <https://github.com/${{ github.repository }}/commit/${{ steps.commit-hash.outputs.this }}|(commit)>'

      - name: Notify failure
        uses: actions-ecosystem/action-slack-notifier@v1
        if: failure()
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ env.channel }}
          message: ':up: <https://github.com/${{ github.repository }}|${{ github.repository }}> の package.json と tag の更新に失敗しました。 ${{ env.mrkdwn_action_log_link }}'
