name: Versioning CI

# Run this workflow every time a new commit pushed to main
on:
  push:
    branches:
      - main

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Node up
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Bump version up
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn version --patch
          git push --tags