name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to tag'
        required: true

jobs:
  update-package-json-and-tag:
    name: Update package.json and tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Node up
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Update package.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn config set version-git-message "%s"
          yarn config set version-tag-prefix ""
          yarn version --new-version ${{ github.event.inputs.version }}
          git push

      - name: Push version tag
        run: git push origin refs/tags/${{ github.event.inputs.version }}
